CRITICAL - 2020-12-06 22:13:15 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:13:35 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:13:41 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:13:58 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:17:45 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:18:02 --> Class 'App\Controllers\personasModel' not found
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-12-06 22:19:25 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(56): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:25:30 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:26:25 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:26:34 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:35:34 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:41:01 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:41:05 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:42:20 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:42:26 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:42:41 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(67): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-12-06 22:45:23 --> Unable to connect to the database.
#0 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\HalconesDeLosOfertones\system\Database\BaseBuilder.php(2249): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#2 C:\xampp\htdocs\HalconesDeLosOfertones\system\Model.php(755): CodeIgniter\Database\BaseBuilder->insert()
#3 C:\xampp\htdocs\HalconesDeLosOfertones\app\Controllers\AdminProyecto.php(66): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(918): App\Controllers\AdminProyecto->alta()
#5 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminProyecto))
#6 C:\xampp\htdocs\HalconesDeLosOfertones\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\HalconesDeLosOfertones\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
